In [1]:
import numpy as np

In [2]:
arr_1d = np.arange(0,20,2)

In [3]:
arr_1d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [5]:
arr_1d.reshape(2,5) 

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [6]:
ar = np.arange(1,13).reshape(2,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])