In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [3]:
type(array_1d)

numpy.ndarray

In [4]:
array_1d.ndim

1

In [5]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
array_2d.ndim

2

In [7]:
array_1d.size

4

In [8]:
array_2d.size

9

In [9]:
array_2d.shape

(3, 3)

In [10]:
array_2d.dtype

dtype('int32')

In [14]:
np_ones = np.ones(5)
print(np_ones)

[1. 1. 1. 1. 1.]


In [15]:
np_ones.dtype

dtype('float64')

In [17]:
np_ones_new = np.ones((3,5))
print(np_ones_new)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
print(np.ones((3,5), dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
print(np.zeros((3,5), dtype=bool))

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [24]:
em_mx = np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.11454530e-321]
 [1.19043964e-311 1.19043964e-311 0.00000000e+000]]
